Script started on Mon Feb 11 21:52:35 2019
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.4.dylib
  Referenced from: /usr/local/bin/zsh
  Reason: image not found
zsh: abort      
]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..aiBegi/python]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hsscript
[J[0mSCRIPT      [Jscript      [J[1;31mscripting[0m/[J[A[0m[27m[24m[3Cscript[King[1m/[0m[0m [?1l>[?2004l
[J]2;scripting]1;scripting[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hlls[?1l>[?2004l
]2;ls -G]1;lsexercise8.py    firstPy.py      first_script.py
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004heexercise8.        e  ppython3 exercise8.py[1m [0m[0m [?1l>[?2004l
]2;python3 exercise8.py]1;python3  File "exercise8.py", line 18
    i ++
       ^
SyntaxError: invalid syntax
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 exercise8.py[?1l>[?2004l
]2;python3 exercise8.py]1;python3Enter name separated by commas: lucas, leo, thais
Enter assignment separated by commas: geografia, lituania, belgica
Enter grades separated by commas: 10,20,  30, , 40   40
Traceback (most recent call last):
  File "exercise8.py", line 16, in <module>
    message.format(names[i], assignment[i], grades[i], grades[i+1])
NameError: name 'assignment' is not defined
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 exercise8.py[?1l>[?2004l
]2;python3 exercise8.py]1;python3Enter name separated by commas: lucas, leo, thais
Enter assignment separated by commas: ab, bc, cd
Enter grades separated by commas: 10,20,30,40
Traceback (most recent call last):
  File "exercise8.py", line 16, in <module>
    print(message.format(names[i], assignment[i], grades[i], grades[i+1]))
NameError: name 'assignment' is not defined
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 exercise8.py[?1l>[?2004l
]2;python3 exercise8.py]1;python3Enter name separated by commas: lu  Lucas, leo, thais
Enter assignment separated by commas: ab,bc,cd
Enter grades separated by commas: 10,20,30,40
Hi Lucas,

This is a reminder that you have Ab assignments left to submit before you can graduate. You're current grade is 10 and can increase to 20 if you submit all assignments before the due date.


Hi  Leo,

This is a reminder that you have Bc assignments left to submit before you can graduate. You're current grade is 20 and can increase to 30 if you submit all assignments before the due date.


Hi  Thais,

This is a reminder that you have Cd assignments left to submit before you can graduate. You're current grade is 30 and can increase to 40 if you submit all assignments before the due date.


[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 exercise8.py[?1l>[?2004l
]2;python3 exercise8.py]1;python3Enter names separated by commas: lucas, thais, fernando
Enter assignment counts separated by commas: 2, 3, 1
Enter grades separated by commas: 10  8, 5 ,2
Hi Lucas,

This is a reminder that you have 2 assignments left to submit before you can graduate. You're current grade is 8 and can increase to 12 if you submit all assignments before the due date.


Hi  Thais,

This is a reminder that you have  3 assignments left to submit before you can graduate. You're current grade is  5  and can increase to 11 if you submit all assignments before the due date.


Hi  Fernando,

This is a reminder that you have  1 assignments left to submit before you can graduate. You're current grade is 2 and can increase to 4 if you submit all assignments before the due date.


[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hppython3 reading.py[1m [0m[0m [?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 1, in <module>
    f = open('my_path/my_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'my_path/my_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 3, in <module>
    f = open(dirname, 'r')
FileNotFoundError: [Errno 2] No such file or directory: ''
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 3, in <module>
    f = open(dirname, 'r')
TypeError: expected str, bytes or os.PathLike object, not NoneType
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 3, in <module>
    f = open(dirname, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'None'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('my_path/projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'my_path/projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('~/projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '~/projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('~/projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '~/projetos-pessoais/udacity/aiBegi/python/scripting/my_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('~/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '~/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 6, in <module>
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 6, in <module>
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/../some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 6, in <module>
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/..some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3Traceback (most recent call last):
  File "reading.py", line 2, in <module>
    f = open('Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 reading.py[?1l>[?2004l
]2;python3 reading.py]1;python3[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hppython3 tooMany.py[1m [0m[0m [?1l>[?2004l
]2;python3 tooMany.py]1;python3Traceback (most recent call last):
  File "tooMany.py", line 3, in <module>
    files.append(open('my_file.txt', 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'my_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 tooMany.py[?1l>[?2004l
]2;python3 tooMany.py]1;python3Traceback (most recent call last):
  File "tooMany.py", line 3, in <module>
    files.append(open('m/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt', 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'm/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 tooMany.py[?1l>[?2004l
]2;python3 tooMany.py]1;python3Traceback (most recent call last):
  File "tooMany.py", line 3, in <module>
    files.append(open('Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt', 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/some_file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004hpython3 tooMany.py[?1l>[?2004l
]2;python3 tooMany.py]1;python3Traceback (most recent call last):
  File "tooMany.py", line 3, in <module>
    files.append(open('Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/file.txt', 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting/file.txt'
[1m[7m%[27m[1m[0m                                                                                   ]2;lucasbarrozo@MacBook-Pro]1;..hon/scripting]7;file://MacBook-Pro/Users/lucasbarrozo/projetos-pessoais/udacity/aiBegi/python/scripting[0m[27m[24m[J[35mlucasbarrozo[00m[36m@[00m[33mMacBook-Pro[00m[31m:[00m[36m~/projetos-pessoais/udacity/aiBegi/python/scripting[00m[31m|[00m
[36mâ‡’[00m  [K[?1h=[?2004h